const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
(async () => {
  const root = path.resolve(__dirname, '../..');
  const evidence = process.env.CAMPUS_EVIDENCE_NAME || 'map-explorer';
  const out = path.join(root, '06_Demo/screenshots', evidence);
  fs.mkdirSync(out, { recursive: true });
  const browser = await chromium.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', args: ['--enable-unsafe-swiftshader'] });
  const context = await browser.newContext({ viewport: { width: 1440, height: 960 }, reducedMotion: 'reduce' });
  const page = await context.newPage(), checks = [], errors = [];
  page.on('pageerror', e => errors.push(e.message));
  const pass = name => { checks.push(name); console.log('PASS', name); };
  try {
    await page.goto('http://127.0.0.1:7860/');
    await page.waitForFunction(() => document.body.dataset.scene === 'ready');
    await page.waitForFunction(() => document.getElementById('scene').dataset.zoom === '30.00');
    const original = await page.locator('#scene').boundingBox();
    assert.ok(original.width > 1440 * .8);
    pass('Default map uses over 80% viewport width with expanded-campus camera');
    await page.screenshot({ path: path.join(out, 'desktop.png') });
    await page.locator('#map-expand').click();
    assert.equal(await page.locator('#map-expand').getAttribute('aria-pressed'), 'true');
    assert.ok((await page.locator('#scene').boundingBox()).width > original.width);
    assert.equal(await page.locator('.hero-copy').isVisible(), false);
    await page.locator('#map-view').click();
    await page.waitForFunction(() => document.getElementById('scene').dataset.view === 'top');
    await page.screenshot({ path: path.join(out, 'expanded-top.png') });
    pass('Expanded map and top-down view work with reduced motion');
    await page.locator('#map-labels-toggle').click();
    assert.equal(await page.locator('#scene-labels').isVisible(), false);
    await page.locator('#map-labels-toggle').click();
    assert.equal(await page.locator('#scene-labels').isVisible(), true);
    await page.locator('#zoom-in').click();
    await page.waitForFunction(() => Number(document.getElementById('scene').dataset.zoom) < 30);
    await page.locator('#reset-camera').click();
    await page.waitForFunction(() => document.getElementById('scene').dataset.view === 'perspective' && document.getElementById('scene').dataset.zoom === '30.00');
    pass('Landmark toggle, zoom and camera reset preserve state');
    await page.locator('#map-query').fill('VPN');
    assert.equal(await page.locator('#map-results button').count(), 1);
    await page.locator('#map-query').press('Enter');
    assert.equal(await page.locator('#place-title').innerText(), '网络中心');
    assert.equal(await page.locator('#map-results').isVisible(), false);
    await page.screenshot({ path: path.join(out, 'service.png') });
    pass('Service alias search supports keyboard positioning and detail panel');
    await page.locator('#place-agent').click();
    await page.locator('#agent-root').waitFor({ state: 'visible' });
    await page.waitForFunction(() => document.getElementById('agent-root').shadowRoot.getElementById('message-input').value.includes('长安大学VPN'));
    assert.equal(await page.locator('#knowledge-scope').inputValue(), 'chd_public');
    assert.equal(await page.locator('.message.user').count(), 0);
    pass('Map question transfers to CHD assistant without auto-send');
    await page.locator('#knowledge-scope').selectOption('simulation');
    await page.locator('#message-input').fill('我的原有草稿');
    await page.locator('.campus-return').click();
    await page.locator('#place-agent').click();
    await page.waitForFunction(() => document.getElementById('agent-root').shadowRoot.getElementById('message-input').value.includes('长安大学VPN'));
    assert.match(await page.locator('#message-input').inputValue(), /我的原有草稿/);
    assert.equal(await page.locator('#knowledge-scope').inputValue(), 'chd_public');
    pass('Map handoff changes simulated scope safely and retains draft');
    await page.locator('.campus-return').click();
    await page.locator('#close-place').click();
    await page.locator('#map-query').fill('火星基地');
    assert.match(await page.locator('#map-results').innerText(), /未找到/);
    await page.locator('#map-query').press('Escape');
    await page.locator('#map-expand').focus();
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('#map-expand').getAttribute('aria-pressed'), 'false');
    pass('Empty search and Escape leave a usable map');
    await page.locator('#map-query').fill('');
    await page.setViewportSize({ width: 375, height: 900 });
    await page.screenshot({ path: path.join(out, 'mobile.png') });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await page.locator('#map-expand').click();
    await page.locator('#map-view').click();
    await page.screenshot({ path: path.join(out, 'mobile-expanded.png') });
    for (const id of ['map-expand', 'map-view', 'map-labels-toggle', 'map-query']) {
      const b = await page.locator('#' + id).boundingBox();
      assert.ok(b.x >= 0 && b.x + b.width <= 375 && b.height >= 44);
    }
    await page.locator('#map-query').fill('校园卡');
    await page.locator('#map-results button').click();
    assert.equal(await page.locator('#place-title').innerText(), '生活社区');
    await page.screenshot({ path: path.join(out, 'mobile-service.png') });
    pass('375px map controls fit, meet 44px targets, and locate services');
    const fallback = await context.newPage();
    await fallback.route('**/campus-world.js', route => route.abort());
    await fallback.goto('http://127.0.0.1:7860/');
    await fallback.waitForFunction(() => document.body.dataset.scene === 'fallback');
    assert.equal(await fallback.locator('#map-view').isDisabled(), true);
    await fallback.locator('#map-query').fill('VPN');
    await fallback.locator('#map-results button').click();
    assert.equal(await fallback.locator('#place-title').innerText(), '网络中心');
    pass('WebGL fallback keeps service search and detail navigation usable');
    assert.deepEqual(errors, []);
    pass('No uncaught browser errors');
    fs.writeFileSync(path.join(root, '04_Evaluation', process.env.CAMPUS_EVIDENCE_NAME ? evidence + '_results.json' : 'map_explorer_results.json'), JSON.stringify({ executed_at: new Date().toISOString(), checks, errors, scope: 'Illustrative service map only, not real campus navigation' }, null, 2));
  } finally { await browser.close(); }
})().catch(e => { console.error(e); process.exit(1); });
