const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
(async () => {
  const root = path.resolve(__dirname, '../..');
  const out = path.join(root, '06_Demo/screenshots/chd');
  fs.mkdirSync(out, { recursive: true });
  const browser = await chromium.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', args: ['--enable-unsafe-swiftshader'] });
  const context = await browser.newContext({ viewport: { width: 1440, height: 960 } });
  const page = await context.newPage();
  const checks = [], errors = [];
  const pass = name => { checks.push(name); console.log('PASS', name); };
  page.on('pageerror', e => errors.push(e.message));
  try {
    await page.goto('http://127.0.0.1:7860/#agent');
    await page.locator('#agent-root').waitFor({ state: 'visible' });
    await page.waitForFunction(() => !document.body.classList.contains('navigation-moving'));
    await page.locator('#doc-count').filter({ hasText: '6' }).waitFor();
    assert.equal(await page.locator('#knowledge-scope').inputValue(), 'chd_public');
    assert.equal(await page.locator('#attach-document').isDisabled(), true);
    pass('Fresh workbench defaults to CHD, with upload isolation');
    await page.screenshot({ path: path.join(out, 'desktop.png') });
    await page.locator('#message-input').fill('长安大学VPN系统如何使用？');
    await page.locator('#send-button').click();
    await page.locator('.message.assistant').waitFor();
    assert.match(await page.locator('.answer').innerText(), /长安大学/);
    await page.locator('#toggle-sources').click();
    await page.locator('.source-card a').first().waitFor({ state: 'visible' });
    assert.match(await page.locator('.source-card a').first().getAttribute('href'), /chd\.edu\.cn/);
    const officialId = await page.evaluate(() => localStorage.getItem('campus-current'));
    pass('Live offline RAG response has CHD citation link');
    await page.screenshot({ path: path.join(out, 'sources.png') });
    await page.locator('.campus-return').click();
    await page.waitForFunction(() => document.getElementById('assistant-messages').textContent.includes('官方资料对话已保留'));
    pass('Campus mini-assistant does not reuse official conversation');
    await page.locator('.agent-entry').click();
    await page.locator('#agent-root').waitFor({ state: 'visible' });
    await page.locator('#message-input').fill('保留我的草稿');
    await page.locator('#knowledge-scope').selectOption('simulation');
    await page.locator('#doc-count').filter({ hasText: '12' }).waitFor();
    assert.equal(await page.locator('#message-input').inputValue(), '保留我的草稿');
    assert.equal(await page.evaluate(() => localStorage.getItem('campus-current')), null);
    assert.equal(await page.locator('.message.assistant').count(), 0);
    pass('Scope switch opens new conversation, retains draft and simulation corpus');
    const history = await page.evaluate(async id => (await (await fetch('/api/conversations/' + id)).json()).messages, officialId);
    assert.equal(history.length, 2);
    assert.equal(history[1].data.knowledge_scope, 'chd_public');
    pass('Original school conversation remains in history');
    await page.locator('#knowledge-scope').selectOption('chd_public');
    await page.locator('[data-view="knowledge"]').click();
    await page.locator('.knowledge-card').first().waitFor();
    assert.equal(await page.locator('.knowledge-card').count(), 6);
    await page.locator('.knowledge-card').first().click();
    assert.match(await page.locator('#document-meta').innerText(), /2026-10-01/);
    assert.match(await page.locator('#document-actions a').getAttribute('href'), /chd\.edu\.cn/);
    await page.keyboard.press('Escape');
    pass('Knowledge details display source dates and official link');
    await page.screenshot({ path: path.join(out, 'knowledge.png') });
    await page.locator('[data-view="chat"]').click();
    await page.setViewportSize({ width: 375, height: 900 });
    await page.emulateMedia({ reducedMotion: 'reduce' });
    assert.equal(await page.locator('#agent-root').evaluate(el => el.scrollWidth <= el.clientWidth), true);
    const select = await page.locator('#knowledge-scope').boundingBox();
    assert.ok(select.x >= 0 && select.x + select.width <= 375);
    await page.screenshot({ path: path.join(out, 'mobile.png') });
    pass('375px mobile fits source selector with no horizontal overflow');
    assert.deepEqual(errors, []);
    pass('No uncaught browser errors');
    fs.writeFileSync(path.join(root, '04_Evaluation/chd_scope_results.json'), JSON.stringify({ executed_at: new Date().toISOString(), checks, errors, scope: 'School source selection and provenance; not an LLM quality evaluation' }, null, 2));
  } finally { await browser.close(); }
})().catch(e => { console.error(e); process.exit(1); });
